// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8SsyzZ39SpZqM83_-UM1YVapwKt1N_l8',
    appId: '1:781423071742:web:ffb5584f5eecf056e930af',
    messagingSenderId: '781423071742',
    projectId: 'flawless-beauty-a8b38',
    authDomain: 'flawless-beauty-a8b38.firebaseapp.com',
    storageBucket: 'flawless-beauty-a8b38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGu3nyZHmNvQ7LE5XMZYncJnGAXg1fsec',
    appId: '1:781423071742:android:4520a57f081f1314e930af',
    messagingSenderId: '781423071742',
    projectId: 'flawless-beauty-a8b38',
    storageBucket: 'flawless-beauty-a8b38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATuzGJ5T08yHrMhSu5154nPuHhdURKCY4',
    appId: '1:781423071742:ios:4ad53e10f9acad7ee930af',
    messagingSenderId: '781423071742',
    projectId: 'flawless-beauty-a8b38',
    storageBucket: 'flawless-beauty-a8b38.appspot.com',
    iosBundleId: 'com.example.flawlessBeauty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATuzGJ5T08yHrMhSu5154nPuHhdURKCY4',
    appId: '1:781423071742:ios:531805f8513ad84de930af',
    messagingSenderId: '781423071742',
    projectId: 'flawless-beauty-a8b38',
    storageBucket: 'flawless-beauty-a8b38.appspot.com',
    iosBundleId: 'com.example.flawlessBeauty.RunnerTests',
  );
}
